# Generated by Django 4.2.7 on 2023-11-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
